//! # provcheck-audioseal
//!
//! AudioSeal neural-watermark detection for [`provcheck`].
//! Sibling crate to `provcheck-watermark` (silentcipher); both
//! push results into [`Report::watermarks`](provcheck::report::Report::watermarks)
//! so a single verify pass can report multiple independent
//! detector signals.
//!
//! ## License justification
//!
//! AudioSeal is a Meta FAIR research release (ICML 2024,
//! [arXiv:2401.17264](https://arxiv.org/abs/2401.17264)).
//!
//! - **Code:** [facebookresearch/audioseal](https://github.com/facebookresearch/audioseal)
//!   under the **MIT License** (Copyright © Meta Platforms, Inc.
//!   and affiliates).
//! - **Model weights:** distributed via the [Hugging Face Hub at
//!   `facebook/audioseal`](https://huggingface.co/facebook/audioseal),
//!   originally under CC-BY-NC. On **2024-04-02** Meta
//!   relicensed the weights to **full MIT**, explicitly
//!   permitting commercial use: *"We have updated our license
//!   to full MIT license (including the license for the model
//!   weights)! Now you can use AudioSeal in commercial
//!   application too!"* (AudioSeal `README.md`).
//!
//! Both pieces compose cleanly with provcheck's Apache-2.0
//! workspace license per the policy in
//! `WATERMARK_LICENSE_POLICY.md`. Pre-relicense (CC-BY-NC era)
//! AudioSeal would have been rejected; the 2024-04-02 change
//! makes it eligible.
//!
//! ## Status
//!
//! **Scaffold only.** The detection pipeline (audio decode →
//! STFT → tract-onnx → bit decode) is not yet ported to Rust.
//! [`detect`] currently returns
//! `status: NotDetected, message: "implementation pending"`
//! for any input, including known-marked AudioSeal content.
//! `--require-watermark` therefore fails closed when AudioSeal
//! is the only mark you'd expect.
//!
//! ## Integration checklist
//!
//! When the body of [`detect`] is implemented, the work is the
//! same shape as the silentcipher integration that already
//! shipped — just with AudioSeal's specific parameters:
//!
//! 1. **Model artefact.** Export the AudioSeal detector to
//!    ONNX from `facebookresearch/audioseal` or fetch a
//!    pre-converted ONNX (none was found upstream as of
//!    2026-06-09; conversion is straightforward). Drop the
//!    file at `crates/provcheck-audioseal/models/audioseal-detector.onnx`
//!    and embed with `include_bytes!`.
//! 2. **Sample rate.** AudioSeal trains at 16 kHz. Wire
//!    symphonia → rubato to that rate.
//! 3. **API contract.** The AudioSeal detector takes raw
//!    waveform `[1, 1, samples]` (no STFT front-end — the
//!    model includes its own learned front-end) and returns
//!    `(message: [16 bits], localization: [samples])`. Confirm
//!    against the upstream `Watermarker.from_pretrained` API
//!    before locking in shapes.
//! 4. **Detection rule.** Per the AudioSeal paper: a frame is
//!    marked if the localization probability exceeds a
//!    threshold (paper uses 0.5). Aggregate localization
//!    across the file → fraction of marked samples →
//!    confidence. The 16-bit message is the payload.
//! 5. **Dependencies.** Add `tract-onnx`, `symphonia`,
//!    `rubato`, optionally `realfft` if a front-end is
//!    needed (it isn't for AudioSeal's end-to-end model).
//! 6. **Tests.** Mirror `provcheck-watermark/tests/integration.rs`.
//!    A known-marked AudioSeal fixture (generated by running
//!    `audioseal embed` on any clip) at
//!    `tests/fixtures/audioseal-marked.wav` activates the
//!    end-to-end test.

use std::path::Path;

pub use provcheck::prelude::{WatermarkKind, WatermarkResult, WatermarkStatus};

/// Errors returned by [`detect`]. All non-fatal outcomes —
/// "not audio", decoder errors — are reported on the returned
/// [`WatermarkResult`] via its `message` field. `Error` is
/// reserved for genuinely exceptional cases (file not found,
/// unreadable).
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// The target file could not be opened.
    #[error("file not found or unreadable: {0}")]
    Io(#[from] std::io::Error),
}

/// Run the AudioSeal detector on the file at `path`.
///
/// Returns a populated [`WatermarkResult`] regardless of
/// whether the file is audio. While the implementation is
/// pending, every call returns
/// `status: NotDetected, message: "implementation pending"`
/// for audio inputs, and `"not audio"` for non-audio inputs.
/// The function never panics and only returns `Err` on a true
/// I/O failure.
pub fn detect(path: &Path) -> Result<WatermarkResult, Error> {
    let _ = std::fs::metadata(path)?;

    let message = if looks_like_audio(path) {
        // Honest stub: AudioSeal is admitted under the license
        // policy and the WatermarkKind variant exists, but no
        // detection happens yet. Callers that gate on
        // `--require-watermark` get a deterministic
        // "not detected" answer rather than a false positive.
        "implementation pending — see crate docs"
    } else {
        "not audio"
    };

    Ok(WatermarkResult {
        kind: WatermarkKind::AudioSeal,
        status: WatermarkStatus::NotDetected,
        detected: false,
        confidence: 0.0,
        payload: None,
        brand: None,
        message: Some(message.into()),
    })
}

/// Cheap audio classifier by file extension — mirrors the
/// pre-filter in `provcheck-watermark`. AudioSeal's eventual
/// decoder won't have meaningful opinions about non-audio
/// files; we skip the model entirely on extension to avoid
/// loading a (future) ONNX runtime for nothing.
fn looks_like_audio(path: &Path) -> bool {
    let Some(ext) = path.extension().and_then(|e| e.to_str()) else {
        return false;
    };
    matches!(
        ext.to_ascii_lowercase().as_str(),
        "mp3" | "wav" | "flac" | "aac" | "m4a" | "ogg" | "oga" | "opus" | "wma" | "aiff" | "aif"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn missing_file_is_io_error() {
        let err = detect(Path::new("does_not_exist_audioseal_42.wav")).unwrap_err();
        assert!(matches!(err, Error::Io(_)));
    }

    #[test]
    fn non_audio_returns_not_audio() {
        let mut f = tempfile::Builder::new().suffix(".png").tempfile().unwrap();
        f.write_all(b"\x89PNG\r\n\x1a\n").unwrap();
        let r = detect(f.path()).unwrap();
        assert!(matches!(r.kind, WatermarkKind::AudioSeal));
        assert!(matches!(r.status, WatermarkStatus::NotDetected));
        assert_eq!(r.message.as_deref(), Some("not audio"));
    }

    #[test]
    fn audio_extension_returns_pending_stub() {
        let mut f = tempfile::Builder::new().suffix(".wav").tempfile().unwrap();
        f.write_all(b"RIFF\0\0\0\0WAVE").unwrap();
        let r = detect(f.path()).unwrap();
        assert!(matches!(r.kind, WatermarkKind::AudioSeal));
        assert!(matches!(r.status, WatermarkStatus::NotDetected));
        let msg = r.message.unwrap_or_default();
        assert!(
            msg.contains("pending") || msg.contains("implementation"),
            "expected pending-stub message, got: {msg}"
        );
    }
}
