//! # provcheck-wavmark
//!
//! WavMark neural-watermark detection for [`provcheck`].
//! Sibling crate to `provcheck-watermark` (silentcipher) and
//! `provcheck-audioseal`. Each detector pushes a result into
//! [`Report::watermarks`](provcheck::report::Report::watermarks)
//! so a single verify pass can report multiple independent
//! detector signals.
//!
//! ## License justification
//!
//! WavMark is a 2023 academic release from a multi-author team
//! (paper [arXiv:2308.12770](https://arxiv.org/abs/2308.12770),
//! "WavMark: Watermarking for Audio Generation").
//!
//! - **Code:** [wavmark/wavmark](https://github.com/wavmark/wavmark)
//!   under the **MIT License**.
//! - **Model weights:** distributed inside the [`wavmark` PyPI
//!   package](https://pypi.org/project/wavmark/) under the
//!   same MIT terms. `wavmark.load_model()` returns a PyTorch
//!   `nn.Module` with the weights baked in; the package
//!   `LICENSE` is the same MIT file as the repo.
//!
//! Both pieces compose cleanly with provcheck's Apache-2.0
//! workspace license per the policy in
//! `WATERMARK_LICENSE_POLICY.md`.
//!
//! ## Status
//!
//! **Scaffold only.** The detection pipeline (audio decode →
//! tract-onnx → 32-bit decode) is not yet ported to Rust.
//! [`detect`] returns
//! `status: NotDetected, message: "implementation pending"`
//! for any audio input.
//!
//! ## Integration checklist
//!
//! When the body of [`detect`] is implemented, the work is the
//! same shape as the silentcipher integration that already
//! shipped — just with WavMark's specific parameters:
//!
//! 1. **Model artefact.** Export the WavMark detector to ONNX
//!    from `wavmark.load_model()` via `torch.onnx.export`
//!    (the published package ships only PyTorch checkpoints —
//!    no upstream ONNX as of 2026-06-09). Drop the file at
//!    `crates/provcheck-wavmark/models/wavmark-detector.onnx`
//!    and embed with `include_bytes!`.
//! 2. **Sample rate.** WavMark trains at **16 kHz mono** (per
//!    the README's `aim_sr=16000` and the package's
//!    `file_reader.read_as_single_channel` helper). Wire
//!    symphonia → rubato to that rate.
//! 3. **API contract.** `wavmark.decode_watermark(model, signal)`
//!    returns a 32-bit array per the README: 16 bits of a
//!    fixed pattern + 16 bits of custom payload. The package
//!    detects via correlation against the fixed pattern — a
//!    file is marked iff the recovered first-16-bits match
//!    the known fixed pattern within tolerance.
//! 4. **Detection rule.** Per README: *"Since the pattern
//!    length is 16, the probability of mistakenly identifying
//!    an unwatermarked audio as watermarked is only
//!    1/(2^16) = 0.000015."* The fixed-pattern comparison
//!    is the detection signal; the 16-bit custom payload is
//!    the recovered message. Confidence = fraction of fixed-
//!    pattern bits that matched.
//! 5. **Dependencies.** Add `tract-onnx`, `symphonia`,
//!    `rubato`. No STFT needed — WavMark works on raw 1 s
//!    waveform chunks directly.
//! 6. **Tests.** Mirror `provcheck-watermark/tests/integration.rs`.
//!    A known-marked WavMark fixture (generated by running
//!    `wavmark.encode_watermark` on any clip with a known
//!    16-bit custom payload) at
//!    `tests/fixtures/wavmark-marked.wav` activates the
//!    end-to-end test.

use std::path::Path;

pub use provcheck::prelude::{WatermarkKind, WatermarkResult, WatermarkStatus};

/// Errors returned by [`detect`]. All non-fatal outcomes —
/// "not audio", decoder errors — are reported on the returned
/// [`WatermarkResult`] via its `message` field. `Error` is
/// reserved for genuinely exceptional cases (file not found,
/// unreadable).
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// The target file could not be opened.
    #[error("file not found or unreadable: {0}")]
    Io(#[from] std::io::Error),
}

/// Run the WavMark detector on the file at `path`.
///
/// Returns a populated [`WatermarkResult`] regardless of
/// whether the file is audio. While the implementation is
/// pending, every call returns
/// `status: NotDetected, message: "implementation pending"`
/// for audio inputs, and `"not audio"` for non-audio inputs.
pub fn detect(path: &Path) -> Result<WatermarkResult, Error> {
    let _ = std::fs::metadata(path)?;

    let message = if looks_like_audio(path) {
        "implementation pending — see crate docs"
    } else {
        "not audio"
    };

    Ok(WatermarkResult {
        kind: WatermarkKind::WavMark,
        status: WatermarkStatus::NotDetected,
        detected: false,
        confidence: 0.0,
        payload: None,
        brand: None,
        message: Some(message.into()),
    })
}

fn looks_like_audio(path: &Path) -> bool {
    let Some(ext) = path.extension().and_then(|e| e.to_str()) else {
        return false;
    };
    matches!(
        ext.to_ascii_lowercase().as_str(),
        "mp3" | "wav" | "flac" | "aac" | "m4a" | "ogg" | "oga" | "opus" | "wma" | "aiff" | "aif"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn missing_file_is_io_error() {
        let err = detect(Path::new("does_not_exist_wavmark_42.wav")).unwrap_err();
        assert!(matches!(err, Error::Io(_)));
    }

    #[test]
    fn non_audio_returns_not_audio() {
        let mut f = tempfile::Builder::new().suffix(".png").tempfile().unwrap();
        f.write_all(b"\x89PNG\r\n\x1a\n").unwrap();
        let r = detect(f.path()).unwrap();
        assert!(matches!(r.kind, WatermarkKind::WavMark));
        assert!(matches!(r.status, WatermarkStatus::NotDetected));
        assert_eq!(r.message.as_deref(), Some("not audio"));
    }

    #[test]
    fn audio_extension_returns_pending_stub() {
        let mut f = tempfile::Builder::new().suffix(".wav").tempfile().unwrap();
        f.write_all(b"RIFF\0\0\0\0WAVE").unwrap();
        let r = detect(f.path()).unwrap();
        assert!(matches!(r.kind, WatermarkKind::WavMark));
        assert!(matches!(r.status, WatermarkStatus::NotDetected));
        let msg = r.message.unwrap_or_default();
        assert!(
            msg.contains("pending") || msg.contains("implementation"),
            "expected pending-stub message, got: {msg}"
        );
    }
}
